<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Dell" name="runners.NegativeTest" tests="1" failures="0" timestamp="8 Jun 2016 19:04:27 GMT" time="56.393" errors="1">
  <testcase name="feature" time="56.393" classname="runners.NegativeTest">
    <error type="cucumber.runtime.CucumberException" message="junit.framework.AssertionFailedError">
      <![CDATA[cucumber.runtime.CucumberException: junit.framework.AssertionFailedError
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.fail(Assert.java:64)
	at pages.actions.LoginPageActions.checkLoginDone(LoginPageActions.java:39)
	at steps.LoginSteps.i_succesfully_logged_into_the_website(LoginSteps.java:65)
	at âœ½.Then I succesfully logged into the website(LoginToFreeCharge.feature:15)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runners.NegativeTest -->
